const SETVALID = "IS_VALID";
const SETPHNO = "SET_PHNO";
const SETTOKEN = "SET_TOKEN";
const SETUSER = "SET_USER_ID";
const CLEAR_STORE = 'CLEAR_STORE';


export {SETPHNO,SETTOKEN, SETUSER, SETVALID, CLEAR_STORE}